### ISSUE TITLE
Imglib2 dependency

### ISSUE THREAD

**Issue by tischi** [scijava/pom-scijava#120]
@ctrueden @tpietzsch @frauzufall
Could you maybe help me understanding this?
The current parent pom of Fjii should be `28.0.0`: https://github.com/fiji/fiji/blob/master/pom.xml#L8
That seems to imply `imglib2-5.8.0.jar`: https://github.com/scijava/pom-scijava/blob/pom-scijava-28.0.0/pom.xml#L344
However when I download a fresh Fiji, I have version `imglib2-5.6.3.jar` in my jars folder.

**Comment by ctrueden** [comment]
@tischi Sorry for the confusion. I updated the fiji/fiji git repository to extend pom-scijava 28, and released fiji 2.0.0-pre-11 to the Maven repository. However, I never uploaded those new component versions to the Java-8 update site.

I'm currently working hard on finalizing pom-scijava 29.0.0, and planning to upload all the new components to the update site at that time.

**Comment by tischi** [comment]
Thanks a lot for the clarification! And, btw, thank you for the hard work on making these parent poms. It is beyond my imagination how you even manage to keep everything compatible! Great stuff!
