### ISSUE TITLE
Be careful with jar vs. jar-no-fork lifecycle bindings

### ISSUE THREAD

**Issue by ctrueden** [scijava/pom-scijava#13]
In general, it is better to bind the `jar-no-fork` goal to avoid lifecycle forks. Otherwise, things like enforcer run two or more times, which can slow down the build. We should double check that all places in `pom-scijava` which bind `<goal>jar</goal>` rather than `jar-no-fork` do so with an explicit reason, and document it in XML comments.

**Comment by hinerm** [comment]
:+1:

**Comment by ctrueden** [comment]
Reviewed and addressed in bee6ad2549ac7c806428f8f28a6fcfe3336833f4. Some uses of `<goal>jar</goal>` remain, but I'm calling it "good enough for now."
