### ISSUE TITLE
29.0.0-beta-3 may have a version skew between imglib2-cache and bigdataviewer-vistools?

### ISSUE THREAD

**Issue by axtimwalde** [scijava/pom-scijava#137]
`VolatileViews.wrapAsVolatile(img)` throws a weird `ClassNotFoundException`, details later...

**Comment by ctrueden** [comment]
I believe @tpietzsch has some updates pending relating to these components?

**Comment by axtimwalde** [comment]
That would most likely solve it, I just ran into it and had to roll back to pom-scijava-28.0.0 to get things to work, so I wanted to let you know.

**Comment by tpietzsch** [comment]
@axtimwalde can you give more details? The exception message and a bit of context?

**Comment by axtimwalde** [comment]
Darn, I was hoping for this to just go away without me collecting all the details...

**Comment by axtimwalde** [comment]
Sorry, cannot reproduce this any more, I made too many changes in the meantime.  Sorry for the noise.  Closing this.
