### ISSUE TITLE
Add capability to code-generate license NOTICEs

### ISSUE THREAD

**Issue by hinerm** [scijava/pom-scijava#14]
Throughout the SciJava stack we would like to be able to auto-generate `NOTICE` files, listing the licenses of the dependencies and providing 3rd party license text for any dependency with a differing license.

I believe the [third party](http://www.mojohaus.org/license-maven-plugin/examples/example-thirdparty.html) goal is the starting point for this work.

**Comment by ctrueden** [comment]
I tested `mvn license:add-third-party && cat target/generated-sources/license/THIRD-PARTY.txt` and it works quite well. This only lists the names of licenses of dependencies, though, and not the actual license text.

**Comment by ctrueden** [comment]
I think `license:add-third-party` is good enough in practice.
