### ISSUE TITLE
Add SonarQube plugin dependency

### ISSUE THREAD

**Issue by turekg** [scijava/pom-scijava#140]
<build>
  <pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>3.7.0.1746</version>
      </plugin>
    </plugins>
  </pluginManagement>
</build>

So that can the build can eventually invoke run the plugin against the source code. Will also need to add location of sonarqube server in the settings info on that will be added to this job as soon as I have the info

**Comment by turekg** [comment]
Happy to do all this myself and create a new PR for it

**Comment by ctrueden** [comment]
Sounds good @turekg. Note that the PR should go to scijava/pom-scijava-base, the parent of pom-scijava.

**Comment by ctrueden** [comment]
This was resolved in scijava/pom-scijava-base#25.
