### ISSUE TITLE
Imagej version points to non-existant version

### ISSUE THREAD

**Issue by kephale** [scijava/pom-scijava#148]
https://github.com/scijava/pom-scijava/blob/bed338cc73b46ddc104a4e871537803f700e2461/pom.xml#L419

**Comment by ctrueden** [comment]
> I assume these preemptive version bumps were unintended

I can't remember now, but I think my plan was to cut another pom-scijava release and immediately release new imagej and fiji. However, as @imagejan points out, the commit message makes no sense; probably I had those changes locally and they got accidentally lumped in by an absentminded `-a` flag to `git commit`. Sorry about that.

Anyway, the newest pom-scijava release doesn't have this issue, so fixing it can wait till I'm back from my break. Or if not: please feel free to revert it in the meantime.

**Comment by kephale** [comment]
@ctrueden

No worries, please return to ![](https://media.giphy.com/media/7Y66VN3rtkPtu/giphy.gif)

**Comment by hinerm** [comment]
These versions exist now!
