### ISSUE TITLE
eclipse doesn't like sanitize-version

### ISSUE THREAD

**Issue by hinerm** [scijava/pom-scijava#16]
The [sanitize-version regex](https://github.com/scijava/pom-scijava/blob/8505e8091bbc2e3b07f5e3340036cddf0fb65480/pom.xml#L955-L982) causes annoyances in eclipse, naturally.

```
Plugin execution not covered by lifecycle configuration: org.codehaus.mojo:build-helper-maven-plugin:1.9.1:regex-property (execution: sanitize-version, phase: validate)
```

**Comment by ctrueden** [comment]
Already fixed on master: 208b59cd1dc9b6e67ff7b221e68b57acb9f9359f.

We just need to release and bump version in affected components.
