### ISSUE TITLE
Update scripting-kotlin to 1.4.21

### ISSUE THREAD

**Issue by hinerm** [scijava/pom-scijava#161]
See https://github.com/scijava/scripting-kotlin/pull/4

**Comment by ctrueden** [comment]
Done in scijava/pom-scijava-base@9b27dd8dc4b5b56cb091129f01d50021eb416ab1. Propagated to pom-scijava with 66759e793b11c064d24fecbadf489d6b41c65b05. Released as part of pom-scijava 30.0.0.
