### ISSUE TITLE
Increase `omero-blitz` version and add exclusions to `omero-model`

### ISSUE THREAD

**Issue by ppouchin** [scijava/pom-scijava#173]
Hello, 

Would it be possible to increase `omero-blitz` version to `5.5.8`?
I think the current version leads to IceSSL errors when SSL is configured on the remote server.

Also, to satisfy maven-enforcer-plugin, `omero-model` requires an exclusion apparently (`net.jcip:jcip-annotations:jar:1.0` or `net.sourceforge.findbugs:annotations:jar:1.3.2`), eg:
```
<exclusions>
    <exclusion>
        <groupId>net.jcip</groupId>
        <artifactId>jcip-annotations</artifactId>
    </exclusion>
</exclusions>
```

Best regards, 

Pierre

**Comment by ctrueden** [comment]
@ppouchin So sorry this request slipped through the cracks till now. It's on my list in the near term to get the OMERO artifacts better reconciled with the rest of the SciJava component collection. My goal is to get ImageJ-OMERO working with the newest versions of OMERO, but I'll review the exclusions when I do that (within 2-4 weeks, I estimate). Unfortunately, the OMERO dependencies aren't totally clean, and the needed exclusions have historically changed from version to version, so it's a significant effort to keep pom-scijava updated with it. Perhaps we could reach out to the OMERO team to see if they'd be interested in helping to maintain the exclusions list in pom-scijava more directly.

**Comment by ctrueden** [comment]
Progress on this: see [this forum post](https://forum.image.sc/t/imagej-omero-5-5-5-6-update-site-ready-for-testing/69394) and the corresponding PR https://github.com/imagej/imagej-omero/pull/109. Still need to update pom-scijava's management of OMERO artifacts to match what's in that PR, though, which is more what this issue is about.

**Comment by hinerm** [comment]
@ppouchin we're currently about to go to `omero-blitz` `5.5.10`.. testing a downstream project ([imagej-omero](https://github.com/imagej/imagej-omero)) seems to be fine without any changes to exclusions. If you're running into enforcer problems with `5.5.10` please though please let us know.

**Comment by ctrueden** [comment]
OMERO-related component versions were updated in 0ce3c70abb71eed5362c0c2b10090d4c09472120, thanks to @hinerm. That change facilitated releases of imagej-omero 1.0.0-5.6 and imagej-omero-legacy 1.0.0-5.6, and corresponding uploads to the OMERO-5.6 update site. So I think this issue has finally been tackled. @ppouchin Please let us know how it works for you! :beers:

**Comment by ppouchin** [comment]
Hi, 

It looks like I still have to include this to prevent duplication problems in my pom.xml:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.openmicroscopy</groupId>
                <artifactId>omero-model</artifactId>
                <version>${omero-model.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>net.jcip</groupId>
                        <artifactId>jcip-annotations</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

Maybe I'm doing something wrong though?
