### ISSUE TITLE
JNA version upgrade for Mac M1 chip

### ISSUE THREAD

**Issue by mzouink** [scijava/pom-scijava#201]
I am using a Mac M1 and I have a problem with **j-blosc** and **j-hdf5**
Exception: `(fat file, but missing compatible architecture (have 'i386,x86_64', need 'arm64e'))`
Both of them can be solved by installing the c-blosc using homebrew and specifying it in the JVM runtime params
`-Djna.library.path=/opt/homebrew/Cellar/c-blosc/1.21.1/lib/`
But this only worked with the new version of `jna 5.11.0`
https://github.com/scijava/pom-scijava/blob/da5bc554ecb7be5ed025c83ac1f739e1bdd0c257/pom.xml#L1685
So it is possible to upgrade jna version to 5.11.0 ?

**Comment by mkitti** [comment]
Is it easier to compile and add a new aarch64 binary to JNA 4 ourselves than to upgrade to JNA 5?

**Comment by NicoKiaru** [comment]
Related? There's a checklist by @ctrueden regarding some of the changes involved
https://github.com/scijava/pom-scijava/issues/163

**Comment by ctrueden** [comment]
Closing in favor of #163.
