### ISSUE TITLE
Merge TWS:update-tests

### ISSUE THREAD

**Issue by hinerm** [scijava/pom-scijava#220]
[Trainable Segmentation](https://github.com/fiji/Trainable_Segmentation/tree/update-tests) needs ImageJ 1.53u to complete its updated unit tests.

It can then be re-enabled in melting pot.

**Comment by ctrueden** [comment]
Fixed in fiji/Trainable_Segmentation@ff41b4f5a9d38bdad83b493345e12097924e7eeb.
