### ISSUE TITLE
Please release 38.0.0

### ISSUE THREAD

**Issue by mkitti** [scijava/pom-scijava#272]
Happy Father's Day.

Please release a new version of pom-scijava at your earliest convenience. We could use this for n5-zstandard support.

**Comment by hinerm** [comment]
Closed in https://github.com/scijava/pom-scijava/releases/tag/pom-scijava-38.0.0

Builds should propagate the artifacts shortly!

**Comment by hinerm** [comment]
Well, just kidding... it looks like the deploy [job failed](https://github.com/scijava/pom-scijava/actions/runs/9779222838/job/26997936633).

Something is wrong with the sonatype authentication. :(

**Comment by ctrueden** [comment]
The 38.0.0 release did not succeed due to a change in OSS Sonatype deployment configuration requirements, but I have addressed the issue in the SciJava build script and now released [38.0.1](https://s01.oss.sonatype.org/#nexus-search;gav~org.scijava~pom-scijava~38.0.1~~).
