### ISSUE TITLE
Consider using the GitHub Release Maven Plugin

### ISSUE THREAD

**Issue by ctrueden** [scijava/pom-scijava#3]
The [GitHub Release Maven Plugin](https://jutzig.wordpress.com/2014/01/30/github-release-maven-plugin/) integrates [GitHub Releases](https://github.com/blog/1547-release-your-software) with Maven deployment. We should consider leveraging this plugin to make it easy to release SciJava-based software via GitHub Releases.

**Comment by ctrueden** [comment]
Another advantage of doing releases on GitHub is that we could switch to jitpack.io for deploying Maven artifacts.

**Comment by imagejan** [comment]
There's also https://github.com/RagedUnicorn/github-release-maven-plugin as an alternative Maven plugin, which *might* be better suited and has more recent commits.

See also some related discussion [on the `pyimagej` gitter channel](https://gitter.im/imagej/pyimagej?at=6141a4455cfd665e5227547b).

**Comment by ctrueden** [comment]
After seeing Jitpack in action for years, I no longer want to use it. Using cryptographic hashes as versions is too confusing, since they are not sensibly ordered.

I'm also hesitant to embrace GitHub Releases in general, since I'm not sure what the advantages of using it would be. It ties us more tightly to GitHub (something I'm always resistant to do, in case we ever need to switch). We don't need the binary artifact hosting since we already have maven.scijava.org and oss.sonatype.org. It is a place where release notes could go, but we don't really do release notes yet (see [this thread on forum.image.sc](https://forum.image.sc/t/changelogs-release-notes-for-imagej-fiji-scijava-friends/28466) for related discussion), and maybe those should live in a file in the repository itself anyway?

Anyway, I have no plans to work on this, nor has anyone else stepped up, so I'm closing as not planned for now.

**Comment by imagejan** [comment]
Currently, the only benefit I see for creating a 'release' for every 'tag' on GitHub, is that the release versions could be automatically linked to a zenodo.org DOI. There's no need for the GitHub release to contain any binary files (besides the automatically added zipped source) or any release notes or other comments. A minimal, empty release would just allow to cite each component using a DOI, that's all.
In addition (complementary to zenodo, or independent from it), we could adopt the [citation file format](https://citation-file-format.github.io/) and add a `CITATION.cff` file to each repository (in an automated way).
