### ISSUE TITLE
SNAPSHOT dependencies

### ISSUE THREAD

**Issue by tferr** [scijava/pom-scijava#31]
I was trying to adopt [pom-scijava 13.2.0 in SNT](https://github.com/tferr/Simple_Neurite_Tracer/commit/d4bc927) in SNT. After filling all the details the enforcer requires, I still cannot get SNT to build:
```
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-rules) @ Simple_Neurite_Tracer ---
[WARNING] Invalid POM for sc.fiji:pal-optimization:jar:2.0.0, transitive dependencies (if any) will not be available, enable debug logging for more details
[WARNING] Rule 8: org.scijava.maven.plugin.enforcer.RequireReproducibleBuilds failed with message:

The following artifacts either - are SNAPSHOT versions (V), contain 
SNAPSHOT parents (P), or contain SNAPSHOT dependencies (D):

 Failed to build pom. Failed to build pom. Failed to build pom. sc.fiji:pal-optimization:2.0.0
 (D)  sc.fiji:VIB-lib:2.1.1
 (D)  sc.fiji:VIB_:3.0.1

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] 
```
I guess I could use:
```xml
	<properties>
		<enforcer.skip>true</enforcer.skip>
	</properties>
```
But is there a more _proper_ way to address it?

**Comment by ctrueden** [comment]
Huh, that's a strange message. I wonder if there was some network error, or some corruption in your `~/.m2/repository` cache?

Anyway, starting from your attempt, I pushed a commit to master updating to pom-scijava 13.2.1: a2f9eb91000b6d45f256c6788a35623e9b4e2bf4.

It builds successfully on my system, as well as [on Jenkins](http://jenkins.imagej.net/job/Simple_Neurite_Tracer/55/). If you continue to have trouble building locally, please ping me and we can troubleshoot.

**Comment by tferr** [comment]
Thanks!
Just for future reference, in case this happens to someone else: All good after `rm -rf ~/.m2/repository`. I had tried `mvn clean; mvn eclipse:clean eclipse:eclipse` before filing the issue to no avail. Removing the entire `~/.m2/repository` directory was the only thing that solved it, so thanks again!
