### ISSUE TITLE
Update opencsv version

### ISSUE THREAD

**Issue by imagejan** [scijava/pom-scijava#42]
Currently we define [`<opencsv.version>2.4</opencsv.version>`](https://github.com/scijava/pom-scijava/blob/829ccfcee13ee4961a4de59dc2eaafb059e3e4a9/pom.xml#L699-L700) and [`<groupId>au.com.bytecode</groupId>`](https://github.com/scijava/pom-scijava/blob/829ccfcee13ee4961a4de59dc2eaafb059e3e4a9/pom.xml#L2503-L2504), but a [search on github](https://github.com/search?q=opencsv+is%3Aopen+user%3ACellProfiler+user%3AIcy-imaging+user%3Abigdataviewer+user%3Afiji+user%3Aimagej+user%3Aimglib+user%3Aknime-ip+user%3Amaven-nar+user%3Aome+user%3Aopenmicroscopy+user%3Aopenspim+user%3Ascifio+user%3Ascijava+user%3Aslim-curve+user%3Atrakem2+user%3Auw-loci&ref=simplesearch&type=Code) (via `search.imagej.net`) reveals no artifacts that depend on this.

Can we simply change it to:
* `<opencsv.version>3.9</opencsv.version>` and

    ```
    <dependency>
    	<groupId>com.opencsv</groupId>
    	<artifactId>opencsv</artifactId>
    	<version>${opencsv.version}</version>
    </dependency>
    ```

If we need to keep backwards compatibility here, I suggest to define `<opencsv3.version>3.9</opencsv3.version>` or some such.

**Comment by ctrueden** [comment]
This is a question for @bogovicj and @axtimwalde, since the downstream components which use it are [trakem2-tps](https://github.com/saalfeldlab/trakem2-tps), [jitk-tps](https://github.com/saalfeldlab/jitk-tps) and [bigwarp](https://github.com/saalfeldlab/bigwarp).

Relatedly, I guess we should add `saalfeldlab` to the list of orgs searched by search.imagej.net, eh?

**Comment by bogovicj** [comment]
I'll check on our stuff and report back.

> Relatedly, I guess we should add saalfeldlab to the list of orgs searched by search.imagej.net

Makes sense to me.

**Comment by imagejan** [comment]
Alright, changing the group id in these repos should be sufficient, as they use `CSVReader` and `CSVWriter` which should have compatible API (see [2.x javadoc](http://www.cs.swan.ac.uk/~csbob/teaching/java/JavaDemoNetbeans/opencsv-2.3/doc/api/index.html?au/com/bytecode/opencsv/CSVReader.html) and [3.x javadoc](http://opencsv.sourceforge.net/apidocs/index.html?com/opencsv/CSVReader.html)).

(Version 3 introduces the handy `CSVParser` class.)

**Comment by ctrueden** [comment]
Great! Wanna file some PRs? (To expedite that from the CLI: do you know about [hub](https://github.com/github/hub)?)

P.S. I updated search.imagej.net to include saalfeldlab lab just now.

**Comment by bogovicj** [comment]
> Alright, changing the group id in these repos should be sufficient, as they use CSVReader and CSVWriter which should have compatible API (see 2.x javadoc and 3.x javadoc).

This is indeed the case!  @imagejan, I say go for it and make the change you suggested, then I'll update the deps on our end 👍
