### ISSUE TITLE
Consider using Dependabot to automate version bumps

### ISSUE THREAD

**Issue by imagejan** [scijava/pom-scijava#81]
[Dependabot](https://app.dependabot.com) can help keeping dependency versions up to date. (I don't know how well it deals with versions defined in `<properties>` though...) It will submit PRs when newer versions of dependencies are available, and it supports custom Maven repositories. Should we try it out to simplify version management in `pom-scijava`?

**Comment by ctrueden** [comment]
I'm still happy with the current version management process, and iterating on things like the status site. Relying on Dependabot to suggest the correct version bumps for this mammoth BOM makes me nervous, so I'm going to close this issue for now.
