### ISSUE TITLE
Spark fails at runtime because of excluded logging dependencies

### ISSUE THREAD

**Issue by igorpisarev** [scijava/pom-scijava#88]
When using Spark in a pom-scijava based project, it fails at runtime at `SparkConf()` initialization:
`java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory`
`java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder`

These two slf4j dependencies are needed for it to work correctly:
https://github.com/scijava/pom-scijava/blob/7a1f27cee783466ebc3a3cc45d934145388f5eca/pom.xml#L2443-L2450

I understand that they clash with Fiji's choice of the logging framework (see #66) so removing the exclusions is undesirable. Adding Spark was supposed to make it easier to use it in projects, but unfortunately it only makes it more tricky because the user would need to figure out the missing dependencies and include them downstream.

Not sure what's the best way to handle this, but if removing the exclusions is not an option, maybe it would be better to not have Spark in pom-scijava.

**Comment by igorpisarev** [comment]
Minimal example just in case: https://gist.github.com/igorpisarev/6c7c09d77c32763068389960dc318917

**Comment by ctrueden** [comment]
Removing Spark from pom-scijava would increase your pain here, not decrease it. If you want to see why and how, check out the [PR that added Spark in the first place](https://github.com/scijava/pom-scijava/pull/66#issuecomment-428353634).

I am inclined to blame Spark for the logging woes. Libraries are not supposed to declare any specific SLF4J binding—and certainly not supposed to _depend_ on a specific binding, or even the presence of any binding at all. IMHO, the fact that Spark does so is a bug in Spark, and should be reported upstream.

**Comment by igorpisarev** [comment]
Thanks @ctrueden, it's a good idea to bring it up to the Spark community.
I agree that it's great to have Spark integration in pom-scijava without having to deal with duplicate classes. I use uber jar in my Spark-based project and I've set it to allow duplicate classes (which I know is not the best but it works most of the time, and for incompatible duplicates I use shading). This is why I was puzzled at first when Spark code stopped working after bumping the parent version.

I'm going to close this issue then, but I think it's good to have it documented here if people want to use Spark and need to know what extra dependencies are required.

**Comment by ctrueden** [comment]
@igorpisarev I gave this issue some more thought. Right now, the situation with Spark + Bio-Formats is that there is clash between `kryo` and `kryo-shaded`. If we remove the logging-related exclusions you mentioned, we'd then also have a clash between multiple SLF4J bindings (Bio-Formats depends on `logback-classic`, which is similarly evil to Spark's requirement of `slf4j-log4j12` + `jcl-over-slf4j`). But since these two libraries already clash, removing the exclusions does not really make matters any worse. Anyone depending on both will have to make these choices and probably one side or the other will not work anyway.

So: do you still think we should remove the `slf4j-log4j12` and `jcl-over-slf4j` exclusions? If so, I will make a commit doing so.

**Comment by igorpisarev** [comment]
@ctrueden That makes sense! I would still vote for removing the exclusions, because right now every Spark project would need to take special care to include these dependencies back, where they may not cause any problems. I'm aware of the clash with `kryo` version in Bioformats but thought that more artifacts would be affected by the change in logging dependencies.

**Comment by ctrueden** [comment]
> I would still vote for removing the exclusions

Sounds good, done! fa13d93755e887415c6e13f8e198b4324dc61679

> thought that more artifacts would be affected by the change in logging dependencies.

Maybe; I'm not sure. Since you are a Spark user and I am not, please feel free to test the latest pom-scijava master branch now that I have deleted the exclusions.

**Comment by igorpisarev** [comment]
Thanks, I'll give it a try!
